plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'org.literacyapp.handwriting_numbers'
    compileSdk 36

    defaultConfig {
        applicationId "org.literacyapp.handwriting_numbers"
        minSdk 26
        targetSdk 34
        versionCode 1000005
        versionName "1.0.5"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        encoding = "UTF-8"
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation libs.androidx.test.espresso.core
    androidTestImplementation libs.androidx.test.ext.junit
    testImplementation libs.junit
    implementation libs.elimu.content.provider
    implementation libs.elimu.model
    implementation libs.tensorflow.android
    implementation libs.greendao
    implementation libs.androidx.appcompat
    implementation libs.androidx.cardview
    implementation libs.androidx.legacy.support.v4
}
